name: team
version: '1.0'
main: com.example.team.Team
api-version: '1.21'
commands:
  myteam:
    description: 팀 초대/수락/거절
    usage: /myteam <player> | /myteam <accept|deny> <token>
  leaveteam:
    description: 팀에서 나갑니다.
  myteammsg:
    description: 내 짝에게만 메시지를 보냅니다.
    usage: /myteammsg <메시지>
    aliases: [ mtm ]
  teamspawn:
    description: 팀 스폰 설정
  start:
    description: 팀별 텔레포트
  tc:
    description: 팀 채팅 토글
  ping:
    description: 핑 종이 지급
  quickmatch:
    description: 퀵 메칭